version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: user-session-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - user-session-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  # 后端服务
  backend:
    build:
      context: ./user-session-be
      dockerfile: Dockerfile
    container_name: user-session-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0
      - SERVER_PORT=8080
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_INTERVIEW=DEBUG
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - user-session-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - ./logs:/app/logs

  # 前端服务
  frontend:
    build:
      context: ./user-session-fe
      dockerfile: Dockerfile
    container_name: user-session-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - user-session-network
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api

  # Redis管理界面（可选）
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: user-session-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - user-session-network
    profiles:
      - tools

volumes:
  redis_data:
    driver: local

networks:
  user-session-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16