server:
  port: 8080

spring:
  application:
    name: protocol-benchmark
  main:
    banner-mode: off

dgs:
  graphql:
    schema-locations:
      - classpath:schema/*.graphqls
    graphiql:
      enabled: true

logging:
  level:
    root: WARN
    com.simon.benchmark: WARN
