create table users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null unique,
  name varchar(255) not null
);

create table orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  total int not null,
  constraint fk_orders_user foreign key (user_id) references users(id)
);

create table order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  sku varchar(64) not null,
  qty int not null,
  constraint fk_items_order foreign key (order_id) references orders(id)
);

